[[filters]]
name = "All"

[[filters]] # Matches lines containing xyz (ignores case)
name = "Having xyz"
contains = "(?i)xyz"

[[filters]]
name = "Errors"
contains = "(?i)xyz"
starts_with = "Started (?P<matching>POST)?"
ends_with = "Completed (?P<matching>500)?"

#
# For further information on how to use the regex syntax please visit:
# https://doc.rust-lang.org/regex/regex/index.html#syntax
#
