[[filters]]
name = "Everything"

[[filters]] # Matches lines containing xyz (ignores case)
name = "Having xyz"
contains = "(?i)xyz"

[[filters]] # Matches everything between the starts_with and ends_with boundaries
name = "Errors"
starts_with = "Started GET"
ends_with = "Completed 500"

#
# For further information on how to use the regex syntax please visit:
# https://doc.rust-lang.org/regex/regex/index.html#syntax
#
