dist: xenial
language: rust
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose
  - cargo test --verbose
before_install:
  - sudo apt-get install -y libncursesw5-dev libreadline-dev
