[package]
name = "flow"
version = "0.1.0"
authors = ["Daniel Mircea <daniel@viseztrance.com>"]

[[bin]]
name = "flow"
path = "src/main.rs"

[dependencies]
notify = "^2.4.1"
getopts = "0.2"
toml = "0.2"
rustc-serialize = "0.3"

[dependencies.ncurses]
git = "https://github.com/jeaye/ncurses-rs"
rev = "master"
default-features = false
features = ["menu"]
